apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: drkiq
spec:
  selector:
    app: drkiq
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sidekiq
spec:
  selector:
    app: sidekiq
  ports:
    - protocol: TCP
      port: 55555
      targetPort: 55555
status:
  loadBalancer: {}